### PR TITLE
Load config from json file with custom name

### PR DESCRIPTION
**Pull request by Fluttercom**
Extension method that loads configuration from json file with a custom name
See https://github.com/NLog/NLog/issues/4985

### CODE REVIEW

**Comment by snakefoot** [comment]
Think it should be a solution where `$[configsetting}` also works, with lookup in the `appsettings.json`

**Comment by Fluttercom** [comment]
> 

Something like this?
`public static ISetupBuilder LoadConfigurationUsingConfigBuilder(this ISetupBuilder setupBuilder, Func<IConfigurationBuilder> builderFunc)`

**Comment by snakefoot** [comment]
Yes together with string nlogConfigSection = "NLog" as input-parameter.



Sent from my Galaxy



-------- Original message --------
From: Anatoliy Savinov ***@***.***>
Date: 27/06/2022 12:06 (GMT+01:00)
To: "NLog/NLog.Web" ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog.Web] Load config from json file with custom name (PR #805)


Something like this?
public static ISetupBuilder LoadConfigurationUsingConfigBuilder(this ISetupBuilder setupBuilder, Func<IConfigurationBuilder> builderFunc)

**Comment by snakefoot** [comment]
The idea was to make `LoadConfigurationFromAppSettings` call the new method that takes `Func<IConfigurationBuilder>` as input-parameter. And then remove `LoadConfigurationFromJson`.

So `LoadConfigurationFromAppSettings` just calls the new method with this extracted into a local delegate:
```c#
            var builder = new ConfigurationBuilder()
                // Host Configuration
                .SetBasePath(currentBasePath)
                .AddEnvironmentVariables(prefix: "ASPNETCORE_")
                .AddEnvironmentVariables(prefix: "DOTNET_")
                // App Configuration
                .AddJsonFile("appsettings.json", optional, reloadOnChange)
                .AddJsonFile($"appsettings.{environment}.json", optional: true, reloadOnChange: reloadOnChange)
                .AddEnvironmentVariables();
```

**Comment by Fluttercom** [comment]
Removed `LoadConfigurationFromJson` and still left the possibility to define custom filename.
Not sure about correct place of nlog.config fallback, as `LoadConfigurationUsingConfigBuilder` now requires two additional params.

**Comment by snakefoot** [comment]
After looking at the code, then I think it is just easier if you do this in your own application:

```c#
var config = new ConfigurationBuilder().AddJsonFile("nlog.json").Build();
NLog.LogManager.Setup().SetupExtensions(e => e.RegisterNLogWeb()).LoadConfigurationFromSection(config);
```

**Pull request closed without merging**
