### PR TITLE
Removed System.ValueTuple as dependency for .NET Core app 1, add file version to assembly

### LINKED ISSUE #147: Add Assembly file version to NLog.Web
Not present in NLog.web? Should be added

### PR DESCRIPTION
**Pull request by snakefoot**
And fixed FileVersion so resolves #147

### CODE REVIEW

**Comment by snakefoot** [comment]
@304NotModified Ping

**Comment by 304NotModified** [comment]
> fixed FileVersion

Thanks, but as far as I remember, we should update the fileversion every release (when we define it)

Something like 1.0.{buildnumber}

**Comment by snakefoot** [comment]
And that is what I have done. Not sure I understand your comment. Have you looked at the generated Nuget-package?

**Comment by 304NotModified** [comment]
Oops, was confused by `[assembly: AssemblyFileVersion("1.0.0.0")]` in NLog.Web/Properties/AssemblyInfo.cs

**Comment by snakefoot** [comment]
It makes it possible for the existing nuget command in appveyor to succeed in injecting the build number.


Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
checked in NPE, all green :)

THanks!

**Comment by 304NotModified** [comment]
pong!

**Pull request merged**
