### PR TITLE
Fix AppVeyor build for NLog.Web on master branch

### PR DESCRIPTION
**Pull request by snakefoot**
VersionSuffix should also apply for NLog.Web-build

### CODE REVIEW

**Comment by snakefoot** [comment]
Not sure if https://www.nuget.org/packages/NLog.Web/4.8.2 should be unlisted?

**Comment by 304NotModified** [comment]
THanks!

> Not sure if https://www.nuget.org/packages/NLog.Web/4.8.2 should be unlisted?

We don't broke anything, so it's not really a problem. Leave it like that, as we can't create another 4.8.2 after all.

**Comment by snakefoot** [comment]
But it looks like the PR worked. Now we also have:

https://www.nuget.org/packages/NLog.Web/4.8.2-rc1

But strange symbols has not been broken for:

https://www.nuget.org/packages/NLog.Web.AspNetCore/4.8.2-rc1

**Comment by 304NotModified** [comment]
They only break if there are code changes with the same version ;)

**Comment by 304NotModified** [comment]
> But it looks like the PR worked. Now we also have:
> 
> https://www.nuget.org/packages/NLog.Web/4.8.2-rc1

I think I will release the RTM for ASPnetcore soon, so we can focus on other stuff :)

**Comment by snakefoot** [comment]
@304NotModified Thought you wanted to give the `${AspNetRequestPostedBody}` some more attention with splitting MaxContentLength into more parameters and adding ContentType-filter

**Comment by 304NotModified** [comment]
Yes, but I try to keep the aspnet4 and aspnetcore a bit in sync, so therefor releasing 4.8.2 now and we always add those features to another version

**Comment by 304NotModified** [comment]
I think it at least a very good improvement now :)

**Pull request merged**
