### PR TITLE
NLog.AspNetCore ver. 4.9.1

### PR DESCRIPTION
**Pull request by snakefoot**
Think we should release ver. 4.9.1 with NLog.Extension.Logging 1.6.2 and NLog 4.6.8, before upgrading to NLog 4.7

Have not yet bumped version number in this PR (Incase you have other items to merge before release)

### CODE REVIEW

**Comment by snakefoot** [comment]
@304NotModified Could a NLog.Web.AspNetCore ver. 4.9.1 be made before updating to NLog 4.7 ?

**Comment by 304NotModified** [comment]
That's ok. Now on mobile. Should I merge this one or revert something?

**Comment by snakefoot** [comment]
NLog 4.7 have only been committed to dev, and this PR targets master.

**Comment by 304NotModified** [comment]
OK so merge isn't? ;)

**Comment by snakefoot** [comment]
Yes please merge. Will make another PR that includes only the Version-update

**Comment by 304NotModified** [comment]
oops, that was as squash. Revert that and will do a proper merge

**Comment by 304NotModified** [comment]
@snakefoot this is  a squash. sorry about that. Will remove this squash.

**Comment by 304NotModified** [comment]
reverted the squash

**Comment by 304NotModified** [comment]
I guess there is something wrong here:

Bump NLog from 4.6.7 to 4.6.8 in /src/NLog.Web  should be 9ef1b5d9d965b4114d7421be032b17f9e127fb1f, but is here 2340614c818986663737afee0bfcc1e884a73ac6?

**Comment by snakefoot** [comment]
Yes in #536 it looks correct.

**Comment by 304NotModified** [comment]
looks great, I had the same outcome in #537 :)

**Comment by 304NotModified** [comment]
proper merged with  #536 :)

**Comment by snakefoot** [comment]
master-status in Github now also looks correct with 2 commits behind

**Comment by 304NotModified** [comment]
yes I also double checked it. All looks good :)

**Pull request merged**
