### PR TITLE
Added readme to ASP.NET Core package on nuget.org

### PR DESCRIPTION
**Pull request by 304NotModified**
See [Package readme on NuGet.org docs](https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org) and [MSBuild docs](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile)

-  [ ] enable snupgk. But currently leads to [NU5039](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5039) -> 2021-07-24 not fixed yet
- [x] wait for dotnet RTM - undo `image: Visual Studio 2019 Preview`
- [ ] update/split readme for ASP.NET and ASP.NET Core (readme is currently tweaked for ASP.NET Core only)

### CODE REVIEW

**Comment by 304NotModified** [comment]
preview: https://www.nuget.org/packages/NLog.Web.AspNetCore/4.13.0-readme-preview


image

**Comment by 304NotModified** [comment]
Flaky test (tests current date time with minutes)

**Comment by bakgerman** [comment]
Can this be closed now that we have the PR [https://github.com/NLog/NLog.Web/pull/898](https://github.com/NLog/NLog.Web/pull/898)?

**Comment by 304NotModified** [comment]
Yes it does. Thanks!

**Pull request closed without merging**
