### PR TITLE
Enable deterministic build

### PR DESCRIPTION
**Pull request by 304NotModified**
See https://github.com/clairernovotny/DeterministicBuilds

and https://github.com/NLog/NLog.Extensions.Logging/pull/479

### CODE REVIEW

**Comment by 304NotModified** [comment]
it's still `   <repository type="git" url="git://github.com/NLog/NLog.Web" />`, without commit. Same for aspnetcore package. Strange as NLog/NLog.Extensions.Logging#479 works

**Comment by 304NotModified** [comment]
Was still missing this: #642

**Comment by 304NotModified** [comment]
this this with

- https://www.nuget.org/packages/NLog.Web/4.10.0.1888-PR639
- https://www.nuget.org/packages/NLog.Web.AspNetCore/4.10.0.1888-PR639

**Comment by 304NotModified** [comment]
almost:

image

**Comment by 304NotModified** [comment]
same asp.netcore package:

image

**Comment by 304NotModified** [comment]
new tries:

- https://www.nuget.org/packages/NLog.Web/4.10.0.1892-PR639
- https://www.nuget.org/packages/NLog.Web.AspNetCore/4.10.0.1892-PR639

**Comment by 304NotModified** [comment]
NLog.Web is green :tada:

image

**Comment by 304NotModified** [comment]
also green :)

image

**Comment by snakefoot** [comment]
Wow great work!

**Pull request merged**
