### PR TITLE
Added RequestContext + renderer

### PR DESCRIPTION
**Pull request by 304NotModified**
A request context and renderer. The added variables are only valid for one request and is implemented by the `HttpContext.Items`. There will be no data leaks between requests with this approach.

Add variables to the request context:

```c#
RequestContext.Current["a"] = "b"
RequestContext.Current["numer"] = 2;
RequestContext.Current["d2"] = new DateTime(2020,1,30);;
```

to render, which results always in a `string`:

```xml
${aspnet-request-context:a} //"b"
${aspnet-request-context:number} //"2"
${aspnet-request-context:d2:format=yyyy-MM-dd} //"2020-01-30"
```

### CODE REVIEW

**Comment by 304NotModified** [comment]
Feedback about naming and implemention (Singleton) appreciated :)

**Comment by kevindaub** [comment]
It looks good.  It already defines a predefined pattern with HttpContext.Current and is very straight forward.  Only 1 comment.

**Comment by 304NotModified** [comment]
http://csharpindepth.com/Articles/General/Singleton.aspx

**Comment by 304NotModified** [comment]
Also interesting, our competitor uses `properties ` and `stacks` :https://logging.apache.org/log4net/release/manual/contexts.html

**Comment by 304NotModified** [comment]
Waiting for IContext in NLog core

**Comment by 304NotModified** [comment]
Fix this without IContext. Takes really too long.

**Pull request closed without merging**
