### PR TITLE
Improve performance with many threads

### PR DESCRIPTION
**Pull request by 304NotModified**
See https://github.com/NLog/NLog/issues/2064

### CODE REVIEW

**Comment by snakefoot** [comment]
@304NotModified If the usage of ServiceLocator.ServiceProvider should be avoided. Then maybe these should also be fixed:

- AspNetEnvironmentLayoutRenderer.cs
- IISInstanceNameLayoutRenderer.cs

**Comment by 304NotModified** [comment]
thanks will check them!

**Comment by snakefoot** [comment]
@304NotModified Wondering if it would make sense also to add:

```
protected override void CloseLayoutRenderer()
{
   _httpContextAccessor = null;
}
```

**Comment by 304NotModified** [comment]
good idea! Added to https://github.com/NLog/NLog.Web/issues/134

**Pull request merged**
