### PR TITLE
Use LogManager.LoadConfiguration + RC3

### LINKED ISSUE #239: Update to rc5

### LINKED ISSUE #242: Use LogManager.LoadConfiguration
See https://github.com/NLog/NLog/pull/2472

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #242 (Updates to latest NLog.Extensions.Logging ver. 1.0.0-rc07 and also resolves #239)

### CODE REVIEW

**Comment by 304NotModified** [comment]
thanks!

**Comment by snakefoot** [comment]
@304NotModified Can this also be merged?

**Comment by 304NotModified** [comment]
yep, but have to check the version numbers here. It a bit out-dated

**Comment by snakefoot** [comment]
Nothing has happened in NLog.Web since the last dependency update.


Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
I see it should be RC3 and that already in this PR :)

**Comment by 304NotModified** [comment]
thanks!

**Comment by snakefoot** [comment]
@304NotModified Found a bug, when doing AspNetCore1.1 Apps. Then it will fail to automatically register the NLog.Web.AspNetCore-assembly.

**Comment by snakefoot** [comment]
@304NotModified After further investigation, then this was intended behavior (add to manual register assembly):

https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(csproj---vs2017)

I have now created #249 to improve this.

**Pull request merged**
