### PR TITLE
Updated dependencies

### LINKED ISSUE #228: Update to NLog 4.5 RC2, drop NLog 5 references
See also https://github.com/NLog/NLog/issues/2445

### LINKED ISSUE #230: Remove dependency on System.ValueTuple for NetStandard 2.0
Is part of the default package, just like in net471.

### PR DESCRIPTION
**Pull request by 304NotModified**
fixes #228, fixes #230

### CODE REVIEW

**Comment by snakefoot** [comment]
- netstandard1.3 should be removed (along with the dependency Microsoft.Extensions.PlatformAbstractions)

**Comment by 304NotModified** [comment]
Microsoft.Extensions.PlatformAbstractions not needed for .NET standard 1.5?

**Comment by snakefoot** [comment]
> Microsoft.Extensions.PlatformAbstractions not needed for .NET standard 1.5?

Nope it was only included for netstandard1.3

**Comment by 304NotModified** [comment]
ok thx! :)

**Comment by snakefoot** [comment]
> ok thx! :)

You can also remove the NETSTANDARD1_3 code from AssemblyVersionLayoutRenderer.cs

**Comment by 304NotModified** [comment]
I think it's sleep time ;)

**Comment by 304NotModified** [comment]
for some reasons, VS tells me every time:

image

😕

**Pull request merged**
