### PR TITLE
Updated to support netcoreapp2.0

### PR DESCRIPTION
**Pull request by grokky1**
Related to [NLog.Web 172](https://github.com/NLog/NLog.Web/issues/172)

### CODE REVIEW

**Comment by grokky1** [comment]
Discussion point: should we not take this opportunity to simplify things?

If we do this

````csharp
public static void AddNLogWeb(this ILoggingBuilder builder)
{
  builder.AddNLog();                                                 // NEW
  ServiceLocator.ServiceProvider = builder.Services;
}
````

Then instead of 
````csharp
context.HostingEnvironment.ConfigureNLog("nlog.config");
builder.AddNLog();
builder.AddNLogWeb();
````

We can rather have this simpler config
````csharp
context.HostingEnvironment.ConfigureNLog("nlog.config");
builder.AddNLogWeb();
````

**Comment by xperiandri** [comment]
@grokky1, yep, looks better.

**Comment by 304NotModified** [comment]
> @grokky1, yep, looks better.

Indeed. This was a historical things (breaking change).

This is also a breaking change isn't? Can't we add the new method next to it and mark the other one obsolete?

**Comment by grokky1** [comment]
@304NotModified Yes you're right, we should mark the old one obsolete. However! If people still make both calls, then it would call the config code twice. So we need to 1) think of a way around that, or 2) introduce a new name e.g. `AddNLogCore()` or somthing like that... yuck.

However, we can't go ahead with this until we deal with the extensions PR first: https://github.com/NLog/NLog.Extensions.Logging/pull/126

**Comment by 304NotModified** [comment]
> @304NotModified Yes you're right, we should mark the old one obsolete. However! If people still make both calls, then it would call the config code twice. So we need to 1) think of a way around that, or 2) introduce a new name e.g. AddNLogCore() or somthing like that... yuck.

Nothing goes wrong when calling them both, so not a problem :)

**Comment by 304NotModified** [comment]
> However, to proceed we must first deal with the NLog.Extensions PR: NLog/NLog.Extensions.Logging#126

Yes, wasn't there yet. :) Thanks for the reminder.

**Comment by 304NotModified** [comment]
superseded by #181

**Pull request closed without merging**
