### PR TITLE
Release notes - Version 4.8.5

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by 304NotModified** [comment]
Could you please update the `<PackageReleaseNotes>` in the csprojs?

**Comment by 304NotModified** [comment]
(I'm not on PC now)

**Comment by snakefoot** [comment]
Ahh sorry yes. Will fix that when I back at the PC :)


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Could you please update the <PackageReleaseNotes> in the csprojs?

**Comment by snakefoot** [comment]
Have updated the package release notes.

**Comment by 304NotModified** [comment]
Thanks!!

**Comment by 304NotModified** [comment]
Oops wrong branch

**Pull request merged**
