### PR TITLE
ASPNETCORE_ENVIRONMENT takes now precedence over DOTNET_ENVIRONMENT

### PR DESCRIPTION
**Pull request by snakefoot**
See also: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-5.0#environments

image

### CODE REVIEW

**Comment by snakefoot** [comment]
Maybe Azure Pipelines Config must be changed to use Nuget 5.8.0 ?

**Comment by snakefoot** [comment]
Close and re-open to trigger rebuild

**Comment by 304NotModified** [comment]
I think this small behavior change needs a minor version bump

**Comment by 304NotModified** [comment]
It would be nice if we could unit test this. :)

**Comment by snakefoot** [comment]
> It would be nice if we could unit test this. :)

Not sure how to perform mocking with extension-methods.

**Comment by 304NotModified** [comment]
A yes good one. You can't mock extensions (as it's syntactic sugar), the underlying calls should be mocked for that

**Comment by snakefoot** [comment]
Guess one could make an internal extension-method that requires an interface-parameter which is used.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


A yes good one. You can't mock extensions (as it's syntactic sugar), the underlying calls should be mocked for that

**Review by 304NotModified — APPROVED** [review]

**Comment by 304NotModified** [comment]
I've created a new PR for the license, as we needed that also for other repos and thats easier to track (now and in the futher)

**Comment by 304NotModified** [comment]
you're right about the mocking. Environment.GetEnvironmentVariable can't be mocked easily, and if we do, we still can't assert something good as LoadConfigurationFromFile could not be tested easily.

To for now we keep it like this

**Pull request merged**
