### PR TITLE
Lowercase key aspnet render

### PR DESCRIPTION
**Pull request by czd890**
Fixed https://github.com/NLog/NLog.Web/issues/839

### CODE REVIEW

**Comment by snakefoot** [comment]
Like the direction. Possible to get an unit-test ?

**Comment by czd890** [comment]
Hi @snakefoot, added 2 tests for convert the key to lowercase.

**Comment by snakefoot** [comment]
Looks great. Thank you for the contribution.

**Comment by snakefoot** [comment]
Updated wiki-pages:

https://github.com/NLog/NLog/wiki/AspNetRequest-QueryString-Layout-Renderer
https://github.com/NLog/NLog/wiki/AspNetRequest-Cookie-Layout-Renderer
https://github.com/NLog/NLog/wiki/AspNetRequest-Headers-Layout-Renderer
https://github.com/NLog/NLog/wiki/AspNetRequest-RouteParameters-Layout-Renderer
https://github.com/NLog/NLog/wiki/AspNet-Response-Headers-Layout-Renderer
https://github.com/NLog/NLog/wiki/AspNet-Response-Cookie-Layout-Renderer

**Comment by snakefoot** [comment]
NLog.Web.AspNetCore v5.1.1 has been released: https://www.nuget.org/packages/NLog.Web.AspNetCore/5.1.1

**Pull request merged**
