### PR TITLE
Added support for logging nested properties of session items.

### PR DESCRIPTION
**Pull request by Giorgi**

### CODE REVIEW

**Comment by 304NotModified** [comment]
This is a breaking change?

**Comment by Giorgi** [comment]
I guess it is. In the current version it will cause an exception and consequently won't log anything in the log. With this change it will log whatever the nested property refers too so I guess it does not do any harm.

**Comment by 304NotModified** [comment]
Well hou can have session items with a dot? I think it should be backwards compatible.  Maybe an extra boolean?

Also please post an example (config, usage)  thanks!

**Comment by 304NotModified** [comment]
Also unit test is also needed.

**Comment by Giorgi** [comment]
Yes, you are right, you can use dotted names and this is going to break it. Do you think it's better to add a new bool property or create a separate `AspNetSessionNestedValueLayoutRenderer` or `something like that?

**Comment by 304NotModified** [comment]
I prefer the first solution because the code/functionality is highly related.

**Comment by Giorgi** [comment]
OK, I will work on it. Any suggestions about the boolean property name?

**Comment by 304NotModified** [comment]
`isNestedVariable`?

**Comment by Giorgi** [comment]
What about evaluateNestedProperties?

**Comment by 304NotModified** [comment]
EvaluateAsNestedProperties?

**Comment by Giorgi** [comment]
Sounds good.

**Comment by Giorgi** [comment]
@304NotModified Pull Request updated.

**Comment by 304NotModified** [comment]
Thanks! 

I will merge this after some unit tests and example configs.

**Comment by Giorgi** [comment]
To be honest I am not sure how to mock Session. As for example configs do you want me to add it to the main Nlog project or this one?

**Comment by 304NotModified** [comment]
I would like a XML config example in this PR thread. For the wiki and other possible the news post.

**Comment by 304NotModified** [comment]
About mocking `session`, I agree it's with plain .Net difficult. (or just a hell).

I propose to use [Moq](https://www.nuget.org/packages/Moq/) on the unit test project.

**Comment by 304NotModified** [comment]
@Xharze where are the unit tests located for `Nlog.web`? It should be in the repository?

**Comment by Giorgi** [comment]
@304NotModified Here is a sample xml configuration.

To have the nested properties of session object evaluated use the following layout for AspNetSession layout renderer

    <?xml version="1.0" encoding="utf-8" ?>
    <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

        <targets>
            <target name="logfile" xsi:type="File" fileName="file.txt" />
        </targets>

        <rules>
            <logger name="*" minlevel="Info" writeTo="logfile" layout="${aspnet-session:Variable=Username:EvaluateAsNestedProperties=true} ${date} ${message}/>
        </rules>
    </nlog>

Where do I write tests for it?

**Comment by 304NotModified** [comment]
@Xharze we don;t have unit tests in this repos available ?

**Comment by Giorgi** [comment]
@304NotModified  Can you merge it without tests? I don't see any tests for existing code either.

**Comment by 304NotModified** [comment]
note this has been released and documented: https://github.com/NLog/NLog/wiki/AspNetSession-layout-renderer

**Pull request merged**
