### PR TITLE
ASP.NET Core2 Example - Updated blackhole configuration + ${aspnet-appbasepath} + ${aspnet-webrootpath}

### LINKED ISSUE #225: Check and update example for ASP.NET Core 2
see https://github.com/NLog/NLog.Web/issues/221#issuecomment-348282148

### PR DESCRIPTION
**Pull request by snakefoot**
Also updated wiki-page to match this commit:

https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2

Resolves #225

### CODE REVIEW

**Comment by snakefoot** [comment]
@304NotModified Ping

**Comment by snakefoot** [comment]
Whoops two new layoutrenders sneaked into the commit:

```
${aspnet-contentrootpath}
${aspnet-webrootpath}
```

**Comment by snakefoot** [comment]
@304NotModified Ping ?

**Comment by 304NotModified** [comment]
Oops

Merged! Thanks!

**Pull request merged**
