### PR TITLE
 ${aspnet-request-cookie} (without cookienames) will render all cookies

### PR DESCRIPTION
**Pull request by 304NotModified**

### CODE REVIEW

**Comment by snakefoot** [comment]
Maybe have a new option to exclude Cookies ? (GDPR)

**Comment by 304NotModified** [comment]
Good idea, please make a new issue :)

**Comment by snakefoot** [comment]
Btw please rollback the upgrade to AspNetCore 2.2.0. The LongTermSupport LTS version is 2.1. We should hold that version until new LTS version comes.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Good idea, please make a new issue :)

**Comment by snakefoot** [comment]
Created  #472

**Pull request merged**
