### PR TITLE
Fix IHttpContextAccessor warning

### PR DESCRIPTION
**Pull request by 304NotModified**
fixes https://github.com/NLog/NLog.Web/issues/157

### CODE REVIEW

**Comment by snakefoot** [comment]
@304NotModified Could be nice if AspNetLayoutRendererBase.Initialize() generated a warning, when HttpContextAccessor is null (And not a debug message for every property-access). As the initial proposal suggested #133 (but changed during refactoring).

Maybe also move the logic in the AspNetLayoutRendererBase-constructor into AspNetLayoutRendererBase.Initialize().

**Comment by 304NotModified** [comment]
> @304NotModified Could be nice if AspNetLayoutRendererBase.Initialize() generated a warning, when HttpContextAccessor is null (

That was the case and we got multiple tickets for the warning. So now debug and only on usage.

**Comment by snakefoot** [comment]
Did you notice comments like these:

> All logging fields like aspnet-* are not included in logs.

Which actually means the logging is not working, because it has been initialized wrong. Maybe the NLog Example should be fixed to perform proper initialization so the layout-renderer works.

**Comment by 304NotModified** [comment]
The new way (working on it), is less difficult to setup :)

**Comment by Surge001** [comment]
Can't wait on the new way to be released. Please let us know in this trail when released! 
thnx!

**Comment by 304NotModified** [comment]
Yes I will! Hopefully this weekend!

**Pull request merged**
