### PR TITLE
Added "ValuesOnly" property to Cookie and QueryString layout renderers + support for multivalue cookie keys in ASP.NET core

### LINKED ISSUE #294: aspnet-request-cookie Value Only
**Type**: Bug (documentation) / Feature Request

**NLog version**: 4.5.6

**NLog.Web/NLog.Web.AspNetCore version**: 4.5.4

**NLog.Extensions.Logging version**: N/A

**Platform**: ASP.NET Core 2.0

**Current NLog config**:

```
layout="${aspnet-request-cookie:CookieNames=TestCookie}"
```

In case of a BUG:

- What is the current result?
Will print
```
TestCookie=TheCookieValue
```

- What is the expected result?
As per [documentation](https://github.com/NLog/NLog/wiki/AspNetRequest-Cookie-Layout-Renderer), value of the cookie *not including its name* written to the log.
```
TheCookieValue
```

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? No, not an error.

- Please post full exception details (message, stacktrace, inner exceptions): N/A

- Are there any workarounds? No

- Is there a version in which it did work? Don't Know

- Can you help us by writing an unit test? Absolutely

In case of a FEATURE REQUEST:
 
If this is a feature that should be added, perhaps as a flag like `ValueOnly`...

- Why do we need it?
Our logs are parsed and having the key/value pair syntax causes a problem for this. We need the value only if possible.

I'm happy to add this feature if that is OK.

### PR DESCRIPTION
**Pull request by alexangas**
Fixes #294 by adding a ValuesOnly property to AspNetLayoutMultiValueRendererBase and implements it for sub-classes AspNetRequestCookieLayoutRenderer and AspNetRequestQueryStringLayoutRenderer. This also includes a fix for multi-value cookie unit tests that slipped through my previous PR, and simplifies Core vs Full framework implementation and unit tests.

Also fixes unit tests not functioning correctly for full framework AssemblyVersionLayoutRender due to incorrect project references.

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks!

**Comment by alexangas** [comment]
@304NotModified By the way, happy to update wiki for this and also my assembly version work.

**Comment by 304NotModified** [comment]
> @304NotModified By the way, happy to update wiki for this and also my assembly version work.

Please do, you could add: added in NLog.Web / NLog.Web.AspNetCore 4.6 :)

**Comment by alexangas** [comment]
@304NotModified Wiki updated in:

- https://github.com/NLog/NLog/wiki/AssemblyVersion-Layout-Renderer
- https://github.com/NLog/NLog/wiki/AspNetRequest-Cookie-Layout-Renderer
- https://github.com/NLog/NLog/wiki/AspNetRequest-QueryString-Layout-Renderer

Hope it's all OK!

**Pull request merged**
