### PR TITLE
 Fixed bug introduced with IServiceCollection.Replace. Instead use TryAddEnumerable

### PR DESCRIPTION
**Pull request by snakefoot**
Bug was introduced in NLog.Web.AspNetCore ver. 4.8.5 by #459

Also updated the obsolete-descriptions

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks!

**Comment by 304NotModified** [comment]
Maybe this should be 4.8.6? (So to master)

**Comment by snakefoot** [comment]
> Maybe this should be 4.8.6? (So to master)

Depends on how far ver. 4.9.0 is from being complete.

**Comment by 304NotModified** [comment]
Well I like to have the docs and .NET Core 3 things ready for 4.9. Unfortunately I have issues with asp.net core on my machine, so that stalls everything (also the Travis issue is a blocker, maybe skip that one for now)

I will cherry-pick this bugfix for 4.8.6. now

**Comment by 304NotModified** [comment]
note: fixed in 4.8.6 with https://github.com/NLog/NLog.Web/pull/487

**Comment by snakefoot** [comment]
Looks like the same fix has to be made for NLog.Extensions.Hosting (Not NLog.Extension.Logging). Sorry about this


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Well I like to have the docs and .NET Core 3 things ready for 4.9. Unfortunately I have issues with asp.net core on my machine, so that stalls everything (also the Travis issue is a blocker, maybe skip that one for now)

I will cherry-pick this bugfix for 4.8.6. now

**Comment by snakefoot** [comment]
Created PR https://github.com/NLog/NLog.Extensions.Logging/pull/350

**Pull request merged**
