### PR TITLE
Run test for asp.net core on full and core framework, fix unit test build

### LINKED ISSUE #151: Fix build
>  NLog.Web.Tests -> C:\projects\nlogweb\NLog.Web.Tests\bin\Release\NLog.Web.Tests.dll
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\projects\nlogweb\NLog.Web.AspNetCore\NLog.Web.AspNetCore.csproj]
CSC : error CS1705: Assembly 'Microsoft.AspNetCore.Http.Abstractions' with identity 'Microsoft.AspNetCore.Http.Abstractions, Version=1.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.AspNetCore.Http.Features, Version=1.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.AspNetCore.Http.Features' with identity 'Microsoft.AspNetCore.Http.Features, Version=1.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' [C:\projects\nlogweb\NLog.Web.AspNetCore\NLog.Web.AspNetCore.csproj]

after https://github.com/NLog/NLog.Web/pull/150

### PR DESCRIPTION
**Pull request by johnkors**
I think this fixes #151 without breaking it, but I could not run the tests on the machine I'm currently on because they're only target full framework.

### CODE REVIEW

**Comment by johnkors** [comment]
Hm, nope. Brb.

**Comment by johnkors** [comment]
All done, if you're okay with running the test project in 461 instead of 451. 

Not sure why xunit throws a fit with 451 here. The build itself runs fine, but xunit does not. Maybe @bradwilson has some ideas why `dotnet xunit`  would complain about bad references, whereas `dotnet build` does not..?

**Comment by 304NotModified** [comment]
yeah I prefer 451 instead of 461.

**Comment by 304NotModified** [comment]
I see there is a beta3 of xunit 2.3. Maybe we should try that one. 

@johnkors could you reproduce this locally?

**Comment by bradwilson** [comment]
We do not support 4.5.1. Our minimum desktop CLR version (with 2.2+) is 4.5.2.

> The minimum version of .NET required for desktop CLR unit tests is now .NET 4.5.2. This change was made since both 4.5 and 4.5.1 are now out of official support. This change only affects your unit test projects; your production code is still free to target lower versions of .NET.

https://xunit.github.io/releases/2.2

**Comment by johnkors** [comment]
Sorry, I get the same output running 452 as when I run 451. Reading the output,  I'm not sure if it's related to nsubstitute or the xunit runner.

```
 NLog.Web.Tests.LayoutRenderers.AspNetItemValueLayoutRendererTests.VariableFoundRendersValue(expectedValue: (a, 1)) [FAIL]
      System.IO.FileLoadException : Could not load file or assembly 'Microsoft.AspNetCore.Http.Features, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
      Stack Trace:
           at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
           at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
           at System.Reflection.RuntimeMethodInfo.GetParametersNoCopy()
           at System.Reflection.RuntimePropertyInfo.GetIndexParametersNoCopy()
           at System.Reflection.RuntimePropertyInfo.GetIndexParameters()
           at Castle.DynamicProxy.Contributors.MembersCollector.AddProperty(PropertyInfo property, IProxyGenerationHook hook)
           at Castle.DynamicProxy.Contributors.MembersCollector.CollectProperties(IProxyGenerationHook hook)
           at Castle.DynamicProxy.Contributors.MembersCollector.CollectMembersToProxy(IProxyGenerationHook hook)
           at Castle.DynamicProxy.Contributors.ClassProxyTargetContributor.<CollectElementsToProxyInternal>d__2.MoveNext()
           at Castle.DynamicProxy.Contributors.CompositeTypeContributor.CollectElementsToProxy(IProxyGenerationHook hook, MetaType model)
           at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateType(String name, Type[] interfaces, INamingScope namingScope)
           at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
           at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
           at NSubstitute.Proxies.CastleDynamicProxy.CastleDynamicProxyFactory.GenerateProxy(ICallRouter callRouter, Type typeToProxy, Type[] additionalInterfaces, Object[] constructorArguments)
           at NSubstitute.Core.SubstituteFactory.Create(Type[] typesToProxy, Object[] constructorArguments, SubstituteConfig config)
           at NSubstitute.Substitute.For[T](Object[] constructorArguments)
        C:\code\frontend\NLog.Web\NLog.Web.AspNetCore.Tests\LayoutRenderers\AspNetItemValueLayoutRendererTests.cs(83,0): at NLog.Web.Tests.LayoutRenderers.AspNetItemValueLayoutRendererTests.VariableFoundRendersValue(Object expectedValue)
```

And

```
    NLog.Web.Tests.LayoutRenderers.AspNetCookieLayoutRendererTests.KeyFoundRendersValue_Cookie_Mulitple_Items_Flat_Formatting [FAIL]
      System.IO.FileLoadException : Could not load file or assembly 'Microsoft.AspNetCore.Http.Features, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
      Stack Trace:
           at NLog.Web.Tests.LayoutRenderers.AspNetCookieLayoutRendererTests.CreateRenderer(Boolean addKey, Boolean addCookie2)
        C:\code\frontend\NLog.Web\NLog.Web.AspNetCore.Tests\LayoutRenderers\AspNetCookieLayoutRendererTests.cs(87,0): at NLog.Web.Tests.LayoutRenderers.AspNetCookieLayoutRendererTests.KeyFoundRendersValue_Cookie_Mulitple_Items_Flat_Formatting()
```

**Comment by bradwilson** [comment]
That looks like you're missing binding redirects. I'll see if I can see what's going on...

**Comment by bradwilson** [comment]
I get this when doing `dotnet restore`:

```
warning : Detected package downgrade: Microsoft.AspNetCore.Http.Features from 1.0.3 to 1.0.2
```

This almost assuredly points at why you're having binding issues at runtime.

**Comment by bradwilson** [comment]
Once I resolved all the mismatched package versions (see attached screenshot), added a reference to `Microsoft.AspNetCore.Http` in the test project (to fix a build error), and updated the xUnit.net packages to `2.3.0-beta3-*`, everything successfully runs:

```
Detecting target frameworks in NLog.Web.AspNetCore.Tests.csproj...
Building for framework net452...
  NLog.Web.AspNetCore -> C:\Dev\NLog\NLog.Web\NLog.Web.AspNetCore\bin\Debug\net451\NLog.Web.AspNetCore.dll
  NLog.Web.AspNetCore.Tests -> C:\Dev\NLog\NLog.Web\NLog.Web.AspNetCore.Tests\bin\Debug\net452\NLog.Web.AspNetCore.Tests.dll
Running desktop CLR tests for framework net452...
xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
  Discovering: NLog.Web.AspNetCore.Tests
  Discovered:  NLog.Web.AspNetCore.Tests
  Starting:    NLog.Web.AspNetCore.Tests
  Finished:    NLog.Web.AspNetCore.Tests
=== TEST EXECUTION SUMMARY ===
   NLog.Web.AspNetCore.Tests  Total: 58, Errors: 0, Failed: 0, Skipped: 0, Time: 0.429s
```

Whenever you get binding errors, make sure you have the identical version references everywhere. `dotnet restore` will _**usually**_ tell you that you have problems, but not always.

This is the `git diff` of my changes:

image

**Comment by johnkors** [comment]
Thanks for looking, @bradwilson ! Strangely enough, my `dotnet restore` did not produce any warnings about downgrades of the `.Features` package. :/ what version of the SDK are you using..? I'm on 1.0.4.

I'll update this PR with those changes, if you're ok with referring 1.1.1 abstractions packages, @304NotModified ?

**Comment by bradwilson** [comment]
I'm using the 2.0.0-preview1 tooling.

**Comment by bradwilson** [comment]
I don't think you need to upgrade everything to 1.1.1; you just need to make sure everybody matches. I opted for 1.1.1 just to ensure that I could get it all to work.

**Comment by 304NotModified** [comment]
Thanks @johnkors  and @bradwilson !

1.1.1 is fine to me.

**Pull request merged**
