### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by mmaitre314**
Use BSD from https://raw.githubusercontent.com/NLog/NLog/master/LICENSE.txt and update copyright

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks @mmaitre314 

Sorry for the late reply. The problem is here that I'm not the (only) official owner and it's very difficult to contact the real owners. That's also the reason why this license stuff isn't fixed yet :(

**Comment by dabide** [comment]
So does this mean that the NLog.Web is licensed under the GPL?

**Comment by 304NotModified** [comment]
No it's BSD. Discussed that in the past with @Xharze.  But I think @Xharze is the only one who can legally change the headers.

**Comment by 304NotModified** [comment]
Superseded by #48

**Pull request closed without merging**
